# ============================================================
# Setup Android SDK (No Android Studio) + Build APK
# ============================================================
# Requirements: Java JDK 21 (already installed)
# This script downloads Android Command Line Tools and builds the APK
# ============================================================

$ErrorActionPreference = "Continue"

# ---- CONFIGURATION ----
$JAVA_HOME   = "C:\Program Files\Java\jdk-21"
$ANDROID_SDK = "C:\android-sdk"
$CMDLINE_TOOLS_URL = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"
$CMDLINE_TOOLS_ZIP = "$env:TEMP\cmdline-tools.zip"

Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "  Android SDK Setup + APK Build" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan

# ---- Step 1: Set JAVA_HOME ----
Write-Host "`n[1/6] Setting JAVA_HOME..." -ForegroundColor Yellow
$env:JAVA_HOME = $JAVA_HOME
$env:PATH = "$JAVA_HOME\bin;$env:PATH"
java -version 2>&1 | Write-Host
Write-Host "  JAVA_HOME = $env:JAVA_HOME" -ForegroundColor Green

# ---- Step 2: Download Android Command Line Tools ----
Write-Host "`n[2/6] Downloading Android Command Line Tools..." -ForegroundColor Yellow
if (-not (Test-Path "$ANDROID_SDK\cmdline-tools\latest\bin\sdkmanager.bat")) {
    Write-Host "  Downloading from Google..."
    Invoke-WebRequest -Uri $CMDLINE_TOOLS_URL -OutFile $CMDLINE_TOOLS_ZIP -UseBasicParsing
    Write-Host "  Extracting..."
    New-Item -ItemType Directory -Path "$ANDROID_SDK\cmdline-tools" -Force | Out-Null
    Expand-Archive -Path $CMDLINE_TOOLS_ZIP -DestinationPath "$ANDROID_SDK\cmdline-tools" -Force
    # Rename extracted folder to 'latest' (Google zips it as 'cmdline-tools')
    $extracted = Get-ChildItem "$ANDROID_SDK\cmdline-tools" -Directory | Where-Object { $_.Name -ne "latest" } | Select-Object -First 1
    if ($extracted -and $extracted.Name -ne "latest") {
        Rename-Item $extracted.FullName "latest"
    }
    Write-Host "  Done." -ForegroundColor Green
} else {
    Write-Host "  Already downloaded. Skipping." -ForegroundColor Green
}

# ---- Step 3: Set Android SDK environment ----
Write-Host "`n[3/6] Setting Android SDK environment..." -ForegroundColor Yellow
$env:ANDROID_HOME   = $ANDROID_SDK
$env:ANDROID_SDK_ROOT = $ANDROID_SDK
$env:PATH = "$ANDROID_SDK\cmdline-tools\latest\bin;$ANDROID_SDK\platform-tools;$env:PATH"
Write-Host "  ANDROID_HOME = $env:ANDROID_HOME" -ForegroundColor Green

# ---- Step 4: Install required SDK packages ----
Write-Host "`n[4/6] Installing Android SDK packages (accept licenses)..." -ForegroundColor Yellow
# Accept all licenses automatically
$licenseCmd = "& '$ANDROID_SDK\cmdline-tools\latest\bin\sdkmanager.bat' --licenses"
Write-Host "  Accepting SDK licenses..."
"y`ny`ny`ny`ny`ny`ny`ny`ny`ny" | & "$ANDROID_SDK\cmdline-tools\latest\bin\sdkmanager.bat" --licenses 2>&1 | Out-Null

Write-Host "  Installing: platforms;android-34, build-tools;34.0.0, platform-tools..."
& "$ANDROID_SDK\cmdline-tools\latest\bin\sdkmanager.bat" "platforms;android-34" "build-tools;34.0.0" "platform-tools" 2>&1 | Out-Null
Write-Host "  SDK packages installed." -ForegroundColor Green

# ---- Step 5: Update local.properties ----
Write-Host "`n[5/6] Updating local.properties with SDK path..." -ForegroundColor Yellow
$sdkPath = $ANDROID_SDK.Replace("\", "\\")
$localProps = ".\android\local.properties"
$content = @"
## Auto-generated by build script
sdk.dir=$sdkPath
"@
Set-Content -Path $localProps -Value $content
Write-Host "  local.properties updated: sdk.dir=$ANDROID_SDK" -ForegroundColor Green

# ---- Step 6: Build APK ----
Write-Host "`n[6/6] Building Debug APK..." -ForegroundColor Yellow
$env:JAVA_HOME = $JAVA_HOME
Set-Location ".\android"
& ".\gradlew.bat" assembleDebug 2>&1

if ($LASTEXITCODE -eq 0) {
    $apkPath = Get-ChildItem ".\app\build\outputs\apk\debug\*.apk" | Select-Object -First 1
    Write-Host "`n=======================================" -ForegroundColor Green
    Write-Host "  APK BUILT SUCCESSFULLY!" -ForegroundColor Green
    Write-Host "  Location: $($apkPath.FullName)" -ForegroundColor Green
    Write-Host "=======================================" -ForegroundColor Green
} else {
    Write-Host "`nBuild failed. Check error messages above." -ForegroundColor Red
    exit 1
}
